jobs:

- job: buildandtest
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  # publish an artifact called drop
  - task: PublishBuildArtifacts@1


- job: deploy
  pool:
    vmImage: 'ubuntu-16.04'
  dependsOn: buildandtest
  steps:

  # download the artifact drop from the previous job
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: drop

  # deploy to Azure Web App production
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'DevOps Svc'
      appType: 'webApp'
      appName: 'devops-tmcel1118'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      deploymentMethod: 'auto'